-- Seed data for providers table
-- Run this SQL in your Supabase SQL Editor to populate initial provider data

INSERT INTO public.providers (id, name, machine_models, contract_length, settlement_time, auto_renewal, early_termination_fee, fees, turnover_tiers, features, device_info, documents_required, display_order) VALUES
('dojo', 'Dojo', ARRAY['PAX920'], '12 months or no contract', 'Working day and everyday both option', false, NULL, '{"debit": {"min": 0.004, "max": 0.014, "avg": 0.0075}, "credit": {"min": 0.0075, "max": 0.015, "avg": 0.01}, "business_card": null, "tap_fee": [0.02, 0.03, 0.05], "refund_fee": 0.5, "chargeback_fee": 28, "monthly_rental": 15, "maintenance_fee": 5, "dashboard_fee": 10, "pci_fee": 0, "non_compliance_fee": 0, "sim_fee": null, "setup_fee": null, "min_monthly_charge": null}'::jsonb, NULL, ARRAY['Fast settlement options', 'Dashboard access', 'No hidden fees', '12-month or rolling contract'], NULL, NULL, 1),
('sumup', 'SumUp', ARRAY['SumUp Air', 'SumUp Solo'], 'No contract', '2 working days', false, NULL, '{"transaction_fee": 0.0175, "monthly_rental": 0, "setup_fee": 70, "pci_fee": 0, "non_compliance_fee": 0, "sim_fee": 0}'::jsonb, '[{"range": "0–5000", "fee": 0.0175}, {"range": "5000+", "fee": 0.0175}]'::jsonb, ARRAY['Pay-as-you-go model', 'No contract', 'Fast setup', 'Free dashboard access'], NULL, NULL, 2),
('zettle', 'Zettle', ARRAY['Zettle Reader 2'], 'No contract', '2 working days', false, NULL, '{"transaction_fee": 0.0175, "monthly_rental": 0, "setup_fee": 70, "pci_fee": 0, "non_compliance_fee": 0, "sim_fee": 0}'::jsonb, '[{"range": "0–5000", "fee": 0.0175}, {"range": "5000+", "fee": 0.0175}]'::jsonb, ARRAY['No monthly fee', 'Free business app', 'Fast deposits', 'Works with smartphones and tablets'], NULL, NULL, 3),
('square', 'Square', ARRAY['Square Reader', 'Square Terminal'], 'No contract', '2 working days', false, NULL, '{"transaction_fee": 0.0175, "monthly_rental": 0, "setup_fee": 70, "pci_fee": 0, "non_compliance_fee": 0, "sim_fee": 0}'::jsonb, '[{"range": "0–5000", "fee": 0.0175}, {"range": "5000+", "fee": 0.0175}]'::jsonb, ARRAY['Instant setup', 'Free analytics dashboard', 'Simple pricing', 'No monthly fees'], NULL, NULL, 4),
('evo', 'EVO Payments', ARRAY['PAX920', 'Castle Terminal'], '18 months or no contract', 'Next working day', true, 'Remaining rental fees', '{"debit": {"min": 0.005, "max": 0.0145, "avg": 0.0075}, "credit": {"min": 0.007, "max": 0.02, "avg": 0.013}, "business_card": 0.025, "tap_fee": [0.01, 0.02, 0.04, 0.05], "refund_fee": 5, "monthly_rental": 20, "setup_fee": 0, "pci_fee": 0, "non_compliance_fee": 0}'::jsonb, NULL, ARRAY['Next-day settlements', 'Business card support', 'Trusted UK provider'], NULL, NULL, 5),
('handepay', 'Handepay', ARRAY['Castle Terminal'], 'No contract', 'Next working day', true, NULL, '{"debit": {"min": 0.005, "max": 0.0145, "avg": 0.0075}, "credit": {"min": 0.007, "max": 0.02, "avg": 0.013}, "business_card": 0.025, "tap_fee": [0.01, 0.02, 0.04, 0.05], "refund_fee": 5, "monthly_rental": 20, "setup_fee": 0, "pci_fee": 0, "non_compliance_fee": 0}'::jsonb, NULL, ARRAY['No long contracts', 'Next-day payouts', 'Simple pricing', 'Transparent fees'], NULL, NULL, 6),
('takepayments', 'TakePayments', ARRAY['Castle Terminal'], '18 months', 'Next working day', true, 'Remaining rental fees', '{"debit": {"min": 0.005, "max": 0.0145, "avg": 0.0075}, "credit": {"min": 0.007, "max": 0.02, "avg": 0.013}, "business_card": 0.025, "tap_fee": [0.01, 0.02, 0.04, 0.05], "refund_fee": 5, "monthly_rental": 20, "setup_fee": 0, "pci_fee": 0, "non_compliance_fee": 0}'::jsonb, NULL, ARRAY['Fast settlement times', 'Integrated dashboard', 'Custom pricing options'], NULL, NULL, 7),
('clover', 'Clover', ARRAY['Clover Flex', 'Clover Mini'], '18 months (free cancel after 12 months)', 'Next working day', true, 'Remaining rental fees', '{"debit": {"min": 0.003, "max": 0.0145, "avg": 0.0075}, "credit": {"min": 0.007, "max": 0.02, "avg": 0.013}, "business_card": 0.025, "tap_fee": [0.03, 0.04, 0.05], "refund_fee": 5, "chargeback_fee": 28, "monthly_rental": 15, "setup_fee": 70, "dashboard_fee": 10, "pci_fee": 5, "non_compliance_fee": 25, "sim_fee": 10, "min_monthly_charge": 35}'::jsonb, NULL, ARRAY['Next-day settlement', 'Free cancellation after 12 months', 'Smart touchscreen terminals', 'Modern user interface'], NULL, NULL, 8),
('worldpay', 'Worldpay', ARRAY['DX8000', 'Ingenico 5000'], '18 months (can be cancelled after 1 year)', 'Next working day', true, 'Up to £150', '{"debit": {"min": 0.0049, "max": 0.014}, "credit": {"min": 0.0079, "max": 0.016}, "tap_fee": [0.01, 0.02], "refund_fee": 5, "chargeback_fee": 20, "monthly_rental": 14.5, "setup_fee": 0, "dashboard_fee": 10, "pci_fee": 5, "non_compliance_fee": 22.5, "sim_fee": null, "min_monthly_charge": 10}'::jsonb, '[{"range": "0–5000", "fee": 0.0075}, {"range": "5001–34999", "fee": 0.0075}, {"range": "35000–49999", "fee": 0.0065}, {"range": "50000+", "fee": 0.0065}]'::jsonb, ARRAY['Next-day settlement', 'Free first-year rental', 'Optional dashboard portal', 'Established UK provider'], NULL, NULL, 9),
('teya', 'Teya', ARRAY['Teya Go', 'Teya Essential'], 'No contract – cancel anytime', 'Next working day', false, NULL, '{"transaction_fee": 0.012, "monthly_rental": 15, "setup_fee": 0, "tap_fee": 0, "pci_fee": 0, "non_compliance_fee": 0, "min_monthly_charge": 0}'::jsonb, '[{"range": "5000–9999", "fee": 0.012}, {"range": "10000–14999", "fee": 0.01}, {"range": "15000–24999", "fee": 0.009}, {"range": "25000–34999", "fee": 0.008}, {"range": "35000–49999", "fee": 0.007}, {"range": "50000+", "fee": 0.005}]'::jsonb, ARRAY['Next-day settlement', 'No setup or PCI fees', 'No minimum charges', 'Cancel anytime', 'Live app access', 'Fast and reliable terminals', '100% transparent pricing'], '[{"device_name": "Teya Go", "buy_price": 69, "rental_price": 10}, {"device_name": "Teya Essential", "buy_price": 89, "rental_price": 10}]'::jsonb, '{"proof_of_id": true, "proof_of_business": true, "proof_of_address": true}'::jsonb, 10);

-- Example: Add a sample offer for Teya (£50 gift card for businesses under £25k turnover)
-- Uncomment and modify to add offers:
-- INSERT INTO public.provider_offers (provider_id, title, description, badge_text, start_date, end_date, min_turnover, max_turnover, priority) VALUES
-- ('teya', 'Limited Time Offer', 'Get a £50 Amazon gift card when you sign up', '£50 GIFT CARD', NOW(), NOW() + INTERVAL '30 days', 5000, 25000, 10);

-- Example: Add priority rules to favor certain providers for specific turnover ranges
-- Uncomment and modify to add priority rules:
-- INSERT INTO public.priority_rules (min_turnover, max_turnover, provider_id, priority_score) VALUES
-- (5000, 15000, 'sumup', 100),
-- (5000, 15000, 'square', 90),
-- (15000, 50000, 'dojo', 100),
-- (50000, 200000, 'teya', 100);
